### ISSUE TITLE
Re-consider exporting `Deque` data constructor

### ISSUE THREAD

**Issue by danslapman** [nikita-volkov/deque#8]
Absence of public data constructor for Deque makes impossible automatic instance derivation, e.g. `Hashable`

**Comment by nikita-volkov** [comment]
Looks like what you're actually missing is an instance of `Generic`. I've just made a release, which packs both the `Generic` instance and `Hashable`. Does that suffice?

**Comment by danslapman** [comment]
You are right, I need `Generic` instance, I will give it a try

**Comment by nikita-volkov** [comment]
I'm closing this for now. You're welcome to reopen

**Comment by danslapman** [comment]
Just updated to 0.4.3 today, works perfectly, thank You!
